-- ═══════════════════════════════════════════════════════════════════════════
-- SEED · Briefs (distintos por cliente — §5, §10)
-- ═══════════════════════════════════════════════════════════════════════════
-- 4 briefs completos y diferentes. Pesatronic queda SIN brief a propósito
-- (QA: Campañas bloqueado hasta completar el Brief).

insert into briefs
  (client_id, objetivos_comerciales, servicios, productos, ticket_promedio,
   presupuesto_marketing, proceso_comercial, embudo_actual, propuesta_valor,
   diferenciadores, competencia, perfil_cliente, rango_edad, ubicacion,
   pain_points, motivaciones, pilares, tono, formatos_preferidos, que_no_hacer,
   hashtags_habituales, plataformas_activas, frecuencia_semanal,
   horarios_preferidos, objetivo_principal)
values
  -- Kinara
  ('33333333-0000-0000-0000-000000000001',
   'Aumentar reservas en 30% y posicionar el menú de temporada.',
   'Servicio a la mesa, eventos privados, menú de maridaje.',
   'Platos de autor, coctelería de frutas locales.',
   '$25 por persona', '$1200/mes en pauta',
   'Mensaje o reserva online → confirmación → visita → fidelización.',
   'Recomendación boca a boca + Instagram + Google Maps.',
   'La buena mesa se disfruta mejor acompañada.',
   'Cocina de autor con ingredientes andinos; ambiente cálido.',
   'Restaurantes de autor en Quito norte.',
   'Foodies 28-45, ingreso medio-alto, disfrutan salir a comer.',
   '28-45', 'Quito, Ecuador',
   'Encontrar dónde comer algo especial sin arriesgar.',
   'Vivir experiencias gastronómicas memorables.',
   array['Menú de temporada','Detrás de cámara','Reservas'],
   array['cálido','cercano','apetitoso'],
   array['reel','carrusel','historia']::content_type[],
   'No usar humor forzado ni tendencias que no encajen con la marca.',
   array['#KinaraEC','#GastronomiaQuito','#CocinaDeAutor'],
   array['instagram','facebook','tiktok']::platform[],
   6, 'Jue-Sáb 12:00-13:00 y 18:30-19:30', 'Aumentar reservas del fin de semana'),

  -- Velora
  ('33333333-0000-0000-0000-000000000002',
   'Construir comunidad y lanzar la nueva línea de skincare.',
   'Tratamientos faciales, asesoría de rutina, membresías.',
   'Sérum de vitamina C, línea de limpieza facial.',
   '$45 por sesión', '$0 (sin pauta este trimestre)',
   'DM → agenda → sesión → recompra de productos.',
   'Instagram + referidos de clientas.',
   'Sentirte bien empieza por cuidarte.',
   'Rutinas personalizadas con productos de origen natural.',
   'Spas y centros de estética de barrio.',
   'Mujeres 25-40 interesadas en autocuidado.',
   '25-40', 'Quito, Ecuador',
   'No saber qué productos realmente funcionan para su piel.',
   'Verse y sentirse mejor con constancia.',
   array['Tips de skincare','Antes y después','Comunidad'],
   array['inspirador','empático','fresco'],
   array['reel','carrusel','historia']::content_type[],
   'No prometer resultados médicos ni exagerar beneficios.',
   array['#VeloraBrand','#SkincareEc','#RutinaFacial'],
   array['instagram','tiktok']::platform[],
   5, 'Lun-Vie 20:00-21:00', 'Crecer comunidad e interacción'),

  -- ATUK
  ('33333333-0000-0000-0000-000000000003',
   'Vender la nueva colección andina y llegar a turismo consciente.',
   'Venta de piezas de diseño, encargos personalizados.',
   'Bolsos, textiles y accesorios de artesanía andina.',
   '$80 por pieza', '$400/mes en pauta',
   'Descubrimiento en redes → web → compra → recompra/regalo.',
   'Instagram + ferias + web.',
   'Tu estilo habla por ti, con raíces andinas.',
   'Diseño contemporáneo con técnicas artesanales ecuatorianas.',
   'Marcas de moda artesanal y souvenirs.',
   'Personas 25-50 que valoran lo hecho a mano y lo local.',
   '25-50', 'Quito y Cuenca, Ecuador',
   'Encontrar regalos con significado y calidad.',
   'Apoyar lo local y tener piezas únicas.',
   array['Proceso artesanal','Colección','Historias de artesanos'],
   array['auténtico','cálido','orgulloso'],
   array['reel','carrusel','post_imagen']::content_type[],
   'No usar estética genérica de fast fashion.',
   array['#ATUK','#DisenoAndino','#HechoEnEcuador'],
   array['instagram','facebook']::platform[],
   5, 'Mar-Jue 13:00 y Sáb 11:00', 'Impulsar ventas de la colección'),

  -- Lexaval
  ('33333333-0000-0000-0000-000000000004',
   'Generar consultas calificadas de empresas y posicionar autoridad legal.',
   'Asesoría corporativa, laboral y tributaria.',
   'Paquetes de asesoría mensual para empresas.',
   'Consulta desde $150', '$0 (sin pauta)',
   'Contacto → reunión → propuesta → contrato de asesoría.',
   'Referidos + LinkedIn.',
   'La tranquilidad viene de estar bien asesorado.',
   'Respuestas claras, sin jerga, para decisiones empresariales.',
   'Estudios jurídicos tradicionales.',
   'Gerentes y dueños de PYMES que necesitan respaldo legal.',
   '35-55', 'Quito, Ecuador',
   'Riesgo legal por decisiones sin asesoría.',
   'Operar con seguridad jurídica.',
   array['Tips legales','Casos frecuentes','Novedades normativas'],
   array['formal','claro','confiable'],
   array['carrusel','post_imagen']::content_type[],
   'Nada de humor ni tendencias virales; precisión legal siempre.',
   array['#Lexaval','#AsesoriaLegal','#DerechoEmpresarial'],
   array['linkedin','instagram']::platform[],
   3, 'Mar y Jue 09:00-10:00', 'Generar consultas calificadas')
on conflict (client_id) do nothing;
